### DISCUSSION TITLE
BDA results- oversubtraction

### DISCUSSION THREAD

**Discussion by Kincaidr** [ratt-ru/QuartiCal#202] [General]
We are trying to solve the over-subtraction problem we are getting with both BDA and regular averaging. 

For re-cap, the final `K + de` solve images looked like:

Regular time channel left, BDA right:

![image](https://user-images.githubusercontent.com/53697426/191242452-1e2c5f4c-47b5-469a-865b-9f818e5655ff.png)

We suspected that the shorter spacings are picking up a lot of the low-level unmodelled flux that are biasing the solutions towards the sources and over-subtracting as a result. To check this, I did the `K + de` with 750 , 1000, 1450  UV-cuts. Below I have shown these dirty images along with the no-UV-cut dirty image. They are ordered as no uv-cut (top left),  750 (top right), 1000 (bot left), 1450 (bot right) for the two problematic sources :

![image](https://user-images.githubusercontent.com/53697426/191484847-4c980330-e3ae-4596-bc26-97ae81942ba7.png)

Ive found the min for these two sources too see if over-subtraction results and possible trends. I got:
Source 1 (top):
no uvcut: -1.74;  750 uvcut: -1.90; 1000 uvcut: -1.58; 1400 uvcut: -1.75
Source 2 (bottom):
no uvcut: -1.94;  750 uvcut: -1.55; 1000 uvcut: -1.75; 1400 uvcut: -1.88

It seems like increasing the uv-cut is resulting in the same over-subtraction as no-uvcut. Is there any other way I can quantify this over-subtraction?

**Comment by JSKenyon** [comment]
Wait, are the first two images cleaned and the remaining images dirty? The dirty images don't look particularly oversubtracted to me (are they the correct images?). The large holes you are seeing seem much clearer in the deconvolved images but that means it is very difficult to tell where they are coming from. 

Could you please include images of the unaveraged data as a point of comparison? Also which imager are you using? Could you please also post the model images or point me to the fits files - I would like to see the magnitude of the negative components near those sources.
Additionally, I am not sure how severe those UV cuts are. For some reason I feel like they may be quite high, but my practical experience with UV-cuts is limited.

How good is the model for the DDE affected sources? Apologies for the million questions.

**Comment by Kincaidr** [comment]
1.) Yes the first two images are deep cleaned images, and the UV-cutouts were done for the dirty images only to save time. Yes, they do not look as over-subtracted as the deep images (the deep images are about a magnitude more subtracted), but there are still holes there nevertheless, just not as deep as the cleaned ones. Is this not because they are only dirty images?

2.) I can do the un-averaged ones now. I was using WSClean with `niter 0`, so no model was created for the UV-cuts. Yes the UV-cuts are quite high, but this was just for experimental reasons to see if it could make a difference in preventing the over-subtraction.

3.) For the above-cleaned image, the model image with the corresponding cleaned image for the regular average is here:

![image](https://user-images.githubusercontent.com/53697426/191569790-d20e15f6-c1cc-4f1c-9a9c-6ce8a9085c2d.png)

Or you can access it over here `/home/kincaid/xova_analyses_new_timechannel/xova_timechannel/obs1lb/im5` on crosby

**Reply by JSKenyon** [reply]
Great! I have had a dig through the images. What where your solution intervals on the direction dependent term?

**Comment by Kincaidr** [comment]
I used this:

```yml
    quartical_2:
      cab: quartical
      info: "Peel off axis source"
      params:
        input_ms.path: '{recipe.ms}'
        input_ms.is_bda: true
        input_ms.weight_column: WEIGHT_SPECTRUM
        input_ms.time_chunk: 0
        #input_ms.select_uv_range: [1400,0]
        solver.terms: [K,de]
        K.type: phase
        K.direction_dependent: false
        K.freq_interval: '0'
        K.time_interval: '4' 
        de.time_interval: '10'
        K.initial_estimate: false
        de.type: complex
        de.freq_interval: '64'
        solver.iter_recipe: [100,50]
        input_model.recipe: MODEL_DATA~DIR1_DATA~DIR2_DATA~DIR3_DATA:DIR1_DATA:DIR2_DATA:DIR3_DATA
        output.overwrite: 'true'
        output.products: [corrected_data, corrected_residual]
        output.columns: [CORRECTED_DATA,CORRECTED_RESIDUAL]
        output.subtract_directions: [1,2,3]
```
