### DISCUSSION TITLE
Interest in full 1GC calibration workflow with QuartiCal — CASA parallels?

### DISCUSSION THREAD

**Discussion by AKHughes1994** [ratt-ru/QuartiCal#372] [General]
Hi all,

Title really says it all — I’m eager to switch to full QuartiCal workflows. Right now, I use QuartiCal primarily for self-cal, with CASA handling 1GC. I'd love to see if I can move entirely to QuartiCal for 1GC calibration as well.

What I’m looking for is:

- Guidance on structuring a full 1GC workflow in QuartiCal

- Best practices for mirroring CASA’s multi-gaincal/applycal pipelines

- Suggestions for intermediate flagging (e.g., replacing tfcrop, rflag, etc.)

- How to apply calibration tables “on-the-fly” between steps (e.g., solve for K, then B, etc.), does QC auto-handle ordering.

Could this all go into a single YAML file? Are there examples floating around or recommended patterns, that would be hugely helpful.

Thanks in advance

**Comment by JSKenyon** [comment]
Hi @AKHughes1994!

It is definitely possible to use QuartiCal to do 1GC, and it would be really helpful to have more users actively using the functionality as it will help me figure out where the remaining pain points are. I will attempt to offer some guidance on each point above. Please don't hesitate to ask follow up questions. We could also consider a Zoom call at some point if you think that would be helpful.

> Guidance on structuring a full 1GC workflow in QuartiCal

@landmanbester has some examples of using a combination of QuartiCal and Stimela to do 1GC. It is similar to CASA, although we often use QC to describe a chain of terms to solve for in a single run e.g. on the primary calibrator we would typically consider a chain of G, K and B, where:

- G is a `diag_complex` term which is solved for on a per-scan/per-intergration basis over all channels and accounts for the mean phase errors and flux scale.
- K is a `delay` term which models residual delay errors.
- B is a `diag_complex` term which is solved for per-scan/over all scans and with high frequency resolution to account for the bandpass.

The gain solutions derived above can then be interpolated to the target/secondary as needed using the `load_from` parameter which is available on each term.
 
> Best practices for mirroring CASA’s multi-gaincal/applycal pipelines

I think I may need a little more information on this point - I am not a CASA expert. In principle, you can always load and apply, or load and continue solving the QuartiCal gains i.e. if you want to solve for K and check the results before solving for B, you can always load the K term from disk during the B solve by including it in the Jones chain. 

> Suggestions for intermediate flagging (e.g., replacing tfcrop, rflag, etc.)

Stating the obvious, flagging is difficult. QuartiCal doesn't really have the functionality to mimic the CASA routines but it does include an optional MAD flagging step. This looks at the (optionally whitened) residuals and attempts to identify outliers both globally and on specific baselines. The difficulty with this approach is that it presumes that the residuals are approximately Gaussian. It doesn't know when a gain has overfit the data, or when the model is incomplete i.e. some caution is required as it will otherwise tend to flag real emission. There are of course other packages like tricolour or aoflagger which implement the sum-threshold algorithm (among others) and will likely do a better job during the early stages of data reduction. Again @landmanbester likely has some good advice in this regard.
 
> How to apply calibration tables “on-the-fly” between steps (e.g., solve for K, then B, etc.), does QC auto-handle ordering.

Applying calibration tables on the fly should be as simple as using the `term.load_from` option which is available for each term in a chain, unless I have misunderstood your meaning?

Ordering is entirely up to the user when using QuartiCal, as the definition of each term is not strict. The "rule of thumb" ordering, which I believe is consistent with CASA (up to a swap of G and K) is:

- G: flux scale + mean phase
- K: residual delays
- B: bandpass
- X: crosshand phase
- D: leakage

This is, however, not enforced. The ordering in the `solver.terms` field dictates the solution order.

> Could this all go into a single YAML file?

Each run of QuartiCal would be a single .yaml file, so it would really depend on how you were breaking up the problem, and how many calibrator fields you have. I would recommend Stimela for orchestrating a full 1GC workflow using QuartiCal. I have included an (out-of-date) example in the drop-down below. It will likely need some tweaking but I think it demonstrates the idea.

<details>
<summary><b>Stimela Recipe</b></summary>

```yaml
_include:
  - (cultcargo)quartical.yml

opts:
  log:
    dir: logs
    nest: 2
  backend:
    select: native # singularity

first-gen:
  name: 1gc
  info: First generation calibration using QuartiCal.

  assign:
    ms_cals: l.ms
    ms_target: l_moon.ms

  inputs:
    basedir:
      dtype: str
      info: Location to write gain tables
    model-column:
      dtype: str
      default: MODEL_DATA

  steps:
    # NOTE: Setjy done outside i.e. MODEL_DATA is correctly populated. This
    # could be added as a recipe step.
    kgbd:
      cab: quartical
      info: GKB on the primary where
            G = time variable complex gain,
            K = per scan delay
            B = diagonal frequency variable complex gain (bandpass)
            D = frequency varaible complex gain (leakage)
      params:
        input_ms.path: =recipe.ms_cals
        input_ms.time_chunk: 0
        input_ms.freq_chunk: 0
        input_ms.select_uv_range: [0,0]
        input_ms.group_by: [FIELD_ID,DATA_DESC_ID,SCAN_NUMBER]
        input_ms.select_fields: [1]
        input_ms.select_corr: [0, 1, 2, 3]
        input_model.recipe: '{recipe.model-column}'
        input_model.apply_p_jones: false
        solver.terms: [G,K,B,D]
        solver.iter_recipe: [150,150,150,150]
        solver.propagate_flags: false
        solver.robust: false
        solver.threads: 16
        solver.reference_antenna: 2
        output.gain_directory: '{recipe.basedir}/gkb.qc'
        output.log_directory: '{recipe.basedir}/'
        output.overwrite: true
        output.flags: false
        output.apply_p_jones_inv: false
        mad_flags.enable: false
        dask.threads: 2
        dask.scheduler: threads
        G.type: diag_complex
        G.time_interval: 0
        G.freq_interval: 0
        K.type: delay
        K.time_interval: 0
        K.freq_interval: 0
        K.initial_estimate: true
        B.type: diag_complex
        B.time_interval: 0
        B.freq_interval: 1
        B.respect_scan_boundaries: false
        D.type: complex
        D.time_interval: 0
        D.freq_interval: 1
        D.initial_estimate: false
        D.respect_scan_boundaries: false

    # Remove the phase on the G term. This is a bit of a hack for now, but
    # provides an interesting example of running some Python code.
    g_to_abs:
      cab: G2abs
      info: Replace G with abs(G) since we won't need the phase again
      params:
        source: '{recipe.basedir}/gkb.qc/G'

    secondary-phases:
      cab: quartical
      info: Delay and offset on the secondary using solutions from primary.
      params:
        input_ms.path: =recipe.ms_cals
        input_ms.time_chunk: 0
        input_ms.freq_chunk: 0
        input_ms.select_uv_range: [0,0]
        input_ms.group_by: [FIELD_ID,DATA_DESC_ID,SCAN_NUMBER]
        input_ms.select_fields: [2]
        input_model.recipe: #'{recipe.model-column}'
        input_model.apply_p_jones: true
        solver.terms: [G, F, K, B, D]
        solver.iter_recipe: [0, 150, 0, 0, 0]
        solver.propagate_flags: false
        solver.robust: false
        solver.threads: 8
        solver.reference_antenna: 2
        output.gain_directory: '{recipe.basedir}/gfkbd.qc'
        output.log_directory: '{recipe.basedir}/'
        output.overwrite: true
        output.flags: false
        output.apply_p_jones_inv: true
        output.net_gains: [G,K,B,D]
        mad_flags.enable: false
        dask.threads: 4
        dask.scheduler: threads
        G.type: diag_complex  #amp
        G.time_interval: 1
        G.freq_interval: 0
        G.load_from: '{recipe.basedir}/gkb.qc/Ga'
        F.type: delay_and_offset
        F.time_interval: 0
        F.freq_interval: 0
        K.type: delay
        K.time_interval: 1
        K.freq_interval: 0
        K.initial_estimate: false
        K.load_from: '{recipe.basedir}/gkb.qc/K'
        B.type: diag_complex
        B.time_interval: 0
        B.freq_interval: 1
        B.load_from: '{recipe.basedir}/gkb.qc/B'
        D.type: complex
        D.load_from: '{recipe.basedir}/gkb.qc/D'
        D.time_interval: 0
        D.freq_interval: 1
        D.respect_scan_boundaries: false

    crosshand-phases:
      cab: quartical
      info: |
        Derive crosshand phases on pol calibrator while transferring solutions
        derived on other calibrators.
      params:
        input_ms.path: =recipe.ms_cals
        input_ms.time_chunk: 0
        input_ms.freq_chunk: 0
        input_ms.select_uv_range: [0,0]
        input_ms.group_by: [FIELD_ID,DATA_DESC_ID]
        input_ms.select_fields: [0]
        input_model.recipe:
        input_model.apply_p_jones: true
        solver.terms: [G, F, K, B, X, D]
        solver.iter_recipe: [0, 150, 0, 0, 150, 0]
        solver.propagate_flags: false
        solver.robust: false
        solver.threads: 64
        solver.reference_antenna: 2
        output.gain_directory: '{recipe.basedir}/gfkbxd.qc'
        output.log_directory: '{recipe.basedir}/'
        output.overwrite: true
        output.flags: false
        output.apply_p_jones_inv: true
        output.net_gains: [G,K,B,D]
        mad_flags.enable: false
        dask.threads: 1
        dask.scheduler: threads
        G.type: diag_complex  #amp
        G.time_interval: 1
        G.freq_interval: 0
        G.load_from: '{recipe.basedir}/gfkbd.qc/G'
        F.type: delay_and_offset
        F.time_interval: 0
        F.freq_interval: 0
        F.load_from: '{recipe.basedir}/gfkbd.qc/F'
        K.type: delay
        K.time_interval: 1
        K.freq_interval: 0
        K.initial_estimate: false
        K.load_from: '{recipe.basedir}/gfkbd.qc/K'
        B.type: diag_complex
        B.time_interval: 0
        B.freq_interval: 1
        B.load_from: '{recipe.basedir}/gfkbd.qc/B'
        X.type: crosshand_phase_null_v
        X.solve_per: array
        X.time_interval: 0
        X.freq_interval: 1
        X.respect_scan_boundaries: false
        D.type: complex
        D.load_from: '{recipe.basedir}/gfkbd.qc/D'
        D.time_interval: 0
        D.freq_interval: 1
        D.respect_scan_boundaries: false

    transfer:
      cab: quartical
      info: |
        Transfer all solutions to the tager field and form up corrected data.
      params:
        input_ms.path: =recipe.ms_target
        input_ms.time_chunk: 0
        input_ms.freq_chunk: 0
        input_ms.select_uv_range: [0,0]
        input_ms.group_by: [FIELD_ID, DATA_DESC_ID, SCAN_NUMBER]
        input_ms.select_fields: [0]
        input_model.recipe: 
        input_model.apply_p_jones: true
        solver.terms: [G, F, K, B, X, D]
        solver.iter_recipe: [0, 0, 0, 0, 0, 0]
        solver.propagate_flags: false
        solver.robust: false
        solver.threads: 2
        solver.reference_antenna: 2
        output.gain_directory: '{recipe.basedir}/final_transfer.qc'
        output.log_directory: '{recipe.basedir}/'
        output.overwrite: true
        output.products: [corrected_data, corrected_weight]
        output.columns: [CORRECTED_DATA, WEIGHT_SPECTRUM]
        output.flags: false
        output.apply_p_jones_inv: true
        output.net_gains: [G,K,B,D]
        mad_flags.enable: false
        dask.threads: 32
        dask.scheduler: threads
        G.type: diag_complex  #amp
        G.time_interval: 1
        G.freq_interval: 0
        G.load_from: '{recipe.basedir}/gfkbxd.qc/G'
        F.type: delay_and_offset
        F.time_interval: 0
        F.freq_interval: 0
        F.load_from: '{recipe.basedir}/gfkbxd.qc/F'
        K.type: delay
        K.time_interval: 1
        K.freq_interval: 0
        K.initial_estimate: false
        K.load_from: '{recipe.basedir}/gfkbd.qc/K'
        B.type: diag_complex
        B.time_interval: 0
        B.freq_interval: 1
        B.load_from: '{recipe.basedir}/gfkbxd.qc/B'
        X.type: crosshand_phase_null_v
        X.solve_per: array
        X.time_interval: 0
        X.freq_interval: 1
        X.respect_scan_boundaries: false
        X.load_from: '{recipe.basedir}/gfkbxd.qc/X'
        D.type: complex
        D.load_from: '{recipe.basedir}/gfkbxd.qc/D'
        D.time_interval: 0
        D.freq_interval: 1
        D.respect_scan_boundaries: false


cabs:
  G2abs:
    name: G2abs
    flavour: python-code
    image:  # This is a bit dodgy - python-astro doesn't have zarr support.
      name: quartical
      version: 0.2.5-cc0.1.3
    command: |
      import dask
      import dask.array as da
      from daskms.experimental.zarr import xds_to_zarr, xds_from_zarr
      gain_table = '::'.join(source.rsplit('/', 1))
      G = xds_from_zarr(gain_table)
      for g in G:
        g['gains'] = (g.gains.dims, da.abs(g.gains.data))
      abs_gain_table = gain_table.rstrip('G') + 'Ga'
      print(f'Writing to {abs_gain_table}')
      writes = xds_to_zarr(G, abs_gain_table)
      dask.compute(writes)
      print('Done')

      
    inputs:
      source:
        info: The location to fetch G term from
        dtype: URI
        required: true

    outputs:
      {}

  quartical:
    image:
      version: 0.2.5-cc0.1.3  # Use latest QuartiCal release.
```

Any folded content here. It requires an empty line just above it.

</details>
