### ISSUE TITLE
Woes after refactor

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/QuartiCal#253]
**Describe the bug**
I am trying to re-implement my old workflow with the v0.2.0-dev branch. I'll report problems here as I uncover them (unless you would prefer separate issues @JSKenyon?).

**Data description (if applicable)**
Same data as before. Note I am using .zarr format

**To Reproduce**
Can provide parsets and data on request.

**Expected behavior**
Workflow must run through as before

The first issue I encountered was version difficulties. Had to 
```
pip install 'numpy==1.20.3'
$ pip install 'numba==0.56'
```
to silence pip's complaints.

Next issue seems a bit more sinister
```[python]
  File "/home/bester/software/QuartiCal/quartical/calibration/solver.py", line 237, in solver_wrapper
    kwargs["corr_mode"])
    └ {'MODEL_DATA': array([[[[16.27895  +0.j       , 16.27895  +0.j       ]],

              [[16.279366 +0.j       , 16.279366 +0.j    ...

KeyError: 'corr_mode'
```
Could be user error but I'm pretty sure the parset hasn't changed. Here it is for reference
```
input_ms:
  path: /home/bester/projects/ESO137/msdir/ms2_primary.zarr
  data_column: DATA
  sigma_column: SIGMA_SPECTRUM 
  weight_column:
  time_chunk: '0'
  freq_chunk: '0'
  is_bda: false
  group_by:
  - SCAN_NUMBER
  - FIELD_ID
  - DATA_DESC_ID
  select_corr: [0,3]
  select_fields: []
  select_ddids: []
  select_uv_range:
  - 0.150
  - 0.0
input_model:
  recipe: MODEL_DATA
  beam:
  beam_l_axis: X
  beam_m_axis: Y
  invert_uvw: true
  source_chunks: 500
  apply_p_jones: false
output:
  gain_directory: out/ms2gains3.qc
  log_directory: out/ms2logs.qc
  overwrite: true
  products: [residual]
  columns: [RESIDUAL]
  flags: false
  apply_p_jones_inv: false
  subtract_directions:
  net_gains: []
mad_flags:
  enable: false
  threshold_bl: 5.0
  threshold_global: 5.0
  max_deviation: 5.0
solver:
  terms: [G, K, B]
  iter_recipe: [100,100,100, 50, 50, 50, 30, 30, 30, 10, 10, 10]
  propagate_flags: true
  robust: true
  threads: 8
  convergence_fraction: 0.99
  convergence_criteria: 1e-06
  reference_antenna: 43
dask:
  threads: 8
  workers: 1
  address:
  scheduler: threads
G:
  type: 'complex'
  time_interval: 18
  freq_interval: 0
  #load_from: out/gains2.qc/smoothed.qc/G
  #interp_mode: ampphase
  #interp_method: 2dlinear
K:
  type: 'delay'
  time_interval: 0
  freq_interval: 0
  initial_estimate: true
  #load_from: out/gains2.qc/smoothed.qc/K
  #interp_mode: ampphase
  #interp_method: 2dlinear
B:
  type: 'complex'
  time_interval: 0
  freq_interval: 1
  #load_from: out/ms2gains.qc/smoothed.qc/B
  #interp_mode: ampphase
  #interp_method: 2dlinear

```
Any ideas?
