### ISSUE TITLE
One direction had zero phases after DD solve

### ISSUE THREAD

**Issue by Joshuaalbert** [ratt-ru/QuartiCal#282]
**Describe the bug**

I'm getting zero gains for one direction in a DD solve.

**Data description (if applicable)**

The Sky model  is this, and they are placed in two lsm Tigger files, and passed in as part of input (see below)
```bash
# (Name, Type, Ra, Dec, I) = format
A, POINT, 00:00:00.00, +37.07.47.400, 1.0
B, POINT, 00:00:00.00, +37.37.47.400, 1.0
```

**To Reproduce**
```yaml

input_ms:
  path: /dsa/output/input.ms
  data_column: DATA
  weight_column: WEIGHT
  time_chunk: 4 # Controls how much RAM is used, can be unit or number per chunk
  freq_chunk: 32 # can be unit or number per chunk, 0 is all

input_model:
  recipe: /dsa/output/skymodel1.lsm.html:/dsa/output/skymodel2.lsm.html

output:
  gain_directory: /dsa/output/gains
  log_directory: /dsa/output/logs
  log_to_terminal: True
  overwrite: True
  flags: True

dask:
  threads: 0 # Setting to zero (the default) will use all available resources.
  scheduler: "threads" # Apparently "threads" is best for single-node use. "multiprocessing" would be the other.

solver:
  terms: [ "G" ]
  iter_recipe: [ 1000 ] # Using a zero would just "interpolate" the solutions into appropriate gains, e.g. G (independent) -> dE (dependent)
  propagate_flags: True
  robust: False # reweight visibilties using residuals (or something) Ask about it.
  threads: 32 # The total number of threads used will be dask.threads*solver.threads; if this product exceeds the number of available threads, performance will suffer.
  reference_antenna: 0 # reference antenna. No gaurantee that it'll be zero.

G:
  type: phase
  direction_dependent: True
  time_interval: "4"
  freq_interval: "32"
```

**Expected behavior**
Should have non-zero gains for all directions in solve.

**Actual Behaviour**
I get zeros for direction 0, and solutions for direction 1.

I see that the dimension of gains correctly has two directions:
![Screenshot from 2023-06-21 02-20-39](https://github.com/ratt-ru/QuartiCal/assets/14807032/1b182c65-475b-4449-9df2-ea2fa6344d94)

**Version**
quartical 0.2.0
