### ISSUE TITLE
A more General DD Gain Specification

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/QuartiCal#354]
**Describe the problem that the feature should address**
Arrays with multiple antenna types are not supported. Support arrays with multiple antenna types, and other DD Gains (DDGs)

**Describe the solution you'd like**
Allow:
1. Multiple primary beams. Or, just DDGs
2. DDGs to be specified for sets of antennas, e.g 
```yaml
DDG:
  DD1: # apply to all antennas
    file: DDGfile01.fits 
  DD2:
    file: DDGfile02.fits # apply to a subset
    antennas: [1,5,6, 10~15]
  DD3: # apply to a subset
    file: DDGfile03.fits
   antennas: [16~24]
```
