### ISSUE TITLE
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/QuartiCal#97]
```
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                
BLAS : Bad memory unallocation! :  128  0x7f252fe6d000                                                                              
BLAS : Bad memory unallocation! :  128  0x7f24a4dd1000                                                                              BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                BLAS : Program is Terminated. Because you tried to allocate too many memory regions.                                                
BLAS : Bad memory unallocation! :  128  0x7f32fa3e6000                                                                              BLAS : Bad memory unallocation! :  128  0x7f2ae0750000                                                                              
Segmentation fault (core dumped)                                                                                                    
```
BLAS is maths library not English library, clearly. Because you shouldn't start a sentence with a preposition. Admittedly, is lesser sin than gluttony! Because trying to allocate too many memory regions is.

This was on a 32-antenna, 1k channel MeerKAT MS with 128 dask threads. I reduced the threads to 64, and now it runs (in a steady and modest ~80G memory, so I find it odd that having twice the threads caused this gluttony.)

```yml
input_ms:
  path: ../msdir/1627405250_sdp_l0-J2009_2026-corr.ms
  data_column: DATA
  weight_column: WEIGHT_SPECTRUM
  time_chunk: '128s'
  freq_chunk: '1GHz'
  select_fields: []
  select_ddids: []
input_model:
  recipe: MODEL_DATA:DIR1_DATA
  apply_p_jones: true
solver:
  terms: [G,dE]
  iter_recipe: [25,25,25,25,25]
output:
  gain_dir: gains.qc
  products: [corrected_data, corrected_residual]
  columns: [CORR_DATA, RES_DATA]
  net_gain: true
mad_flags:
  enable: false
  threshold_bl: 10
  threshold_global: 12
dask:
  threads: 64
  scheduler: distributed
G:
  type: delay
  direction_dependent: false
  time_interval: '8s'
  freq_interval: '1GHz'
  # load_from:
  # interp_mode: reim
  # interp_method: 2dlinear
dE:
  type: complex
  direction_dependent: true
  time_interval: '128s'
  freq_interval: '50MHz'
```
